#!/usr/bin/env python3
"""Scan repo directories and generate tree-data.js for index.html.

Run: python3 build_tree.py
"""
import os, re, json
from pathlib import Path

ROOT = Path(__file__).parent.resolve()

# Mapping: directory path -> (category label, group-aggregation strategy)
# Strategy "ticker" → group by ticker subdir, enable ticker tag
# Strategy "dirname" → group by parent directory name
# Strategy "annual" → group by year from filename date
CATEGORY_MAP = [
    ("research",                "📊 个股研究",   "ticker"),
    ("notes/space",             "📝 行业笔记",   "dirname"),
    ("notes/美股收盘日报",       "📰 美股收盘日报", "annual"),
]

def extract_date_and_title(filepath: str) -> tuple:
    """Extract date (YYYY-MM-DD) and display title from filename."""
    stem = Path(filepath).stem
    # Try to extract date prefix YYYY-MM-DD or YYYY-MM-DD_
    m = re.match(r"(\d{4}-\d{2}-\d{2})_(.+)", stem)
    if m:
        return m.group(1), m.group(2).replace("_", " ").replace("-", " ")
    m = re.match(r"(\d{4}-\d{2}-\d{2})", stem)
    if m:
        return m.group(1), stem
    return None, stem.replace("_", " ").replace("-", " ")

def ticker_from_dir(dirname: str) -> str:
    """Extract ticker from directory name (e.g., PLTR, RKLB)."""
    return dirname.upper()

def build_tree():
    tree = {}

    for rel_dir, cat_label, strategy in CATEGORY_MAP:
        cat_dir = ROOT / rel_dir
        if not cat_dir.exists():
            continue

        if cat_label not in tree:
            tree[cat_label] = {}

        if strategy == "ticker":
            # research/PLTR/*.md → group by ticker subdir
            for sub in sorted(cat_dir.iterdir()):
                if not sub.is_dir() or sub.name.startswith("."):
                    continue
                ticker = ticker_from_dir(sub.name)
                files = []
                for md in sorted(sub.glob("*.md")):
                    date, title = extract_date_and_title(str(md))
                    files.append({
                        "path": str(md.relative_to(ROOT)),
                        "title": title,
                        "date": date,
                        "ticker": ticker,
                    })
                if files:
                    tree[cat_label][ticker] = files

        elif strategy == "dirname":
            # notes/space/*.md → group by "太空产业"
            group_name = cat_dir.name
            # Friendly display name mapping
            name_map = {"space": "太空产业"}
            display_name = name_map.get(group_name, group_name)
            files = []
            for md in sorted(cat_dir.glob("*.md")):
                date, title = extract_date_and_title(str(md))
                files.append({
                    "path": str(md.relative_to(ROOT)),
                    "title": title,
                    "date": date,
                })
            if files:
                tree[cat_label][display_name] = files

        elif strategy == "annual":
            # notes/美股收盘日报/*.md → group by year from filename date
            files_by_year = {}
            for md in sorted(cat_dir.glob("*.md")):
                date, title = extract_date_and_title(str(md))
                if date:
                    parts = date.split("-")
                    year_key = f"{parts[0]}年{parts[1]}月"
                else:
                    # Fallback: use file modification time
                    import datetime
                    mtime = datetime.datetime.fromtimestamp(md.stat().st_mtime)
                    year_key = f"{mtime.year}年{mtime.month}月"
                if year_key not in files_by_year:
                    files_by_year[year_key] = []
                files_by_year[year_key].append({
                    "path": str(md.relative_to(ROOT)),
                    "title": title,
                    "date": date,
                })
            # Sort groups by year-month descending
            for key in sorted(files_by_year.keys(), reverse=True):
                tree[cat_label][key] = files_by_year[key]

    return tree

def generate_js(tree: dict) -> str:
    """Generate tree-data.js content."""
    js = "// Auto-generated by build_tree.py. Do not edit manually.\n"
    js += f"const TREE_DATA = {json.dumps(tree, ensure_ascii=False, indent=2)};\n"
    return js

def main():
    tree = build_tree()
    js = generate_js(tree)
    output_path = ROOT / "tree-data.js"
    output_path.write_text(js, encoding="utf-8")

    # Count files
    count = 0
    for cat in tree.values():
        for files in cat.values():
            count += len(files)

    print(f"Generated tree-data.js: {count} files across {len(tree)} categories")
    for cat, groups in tree.items():
        cat_count = sum(len(f) for f in groups.values())
        print(f"  {cat}: {cat_count} files")

if __name__ == "__main__":
    main()
