// Auto-generated by build_tree.py. Do not edit manually.
const TREE_DATA = {
  "📊 个股研究": {
    "PLTR": [
      {
        "path": "research/PLTR/2026-07-11_PLTR_buyside-memo.md",
        "title": "PLTR buyside memo",
        "date": "2026-07-11",
        "ticker": "PLTR"
      },
      {
        "path": "research/PLTR/2026-07-12_PLTR_chronicle.md",
        "title": "PLTR chronicle",
        "date": "2026-07-12",
        "ticker": "PLTR"
      }
    ],
    "RKLB": [
      {
        "path": "research/RKLB/2026-07-11_RKLB_buyside-memo.md",
        "title": "RKLB buyside memo",
        "date": "2026-07-11",
        "ticker": "RKLB"
      },
      {
        "path": "research/RKLB/2026-07-12_Peter-Beck_biography.md",
        "title": "Peter Beck biography",
        "date": "2026-07-12",
        "ticker": "RKLB"
      },
      {
        "path": "research/RKLB/2026-07-12_RKLB_corporate-chronicle.md",
        "title": "RKLB corporate chronicle",
        "date": "2026-07-12",
        "ticker": "RKLB"
      },
      {
        "path": "research/RKLB/2026-07-12_RKLB_investment-audit.md",
        "title": "RKLB investment audit",
        "date": "2026-07-12",
        "ticker": "RKLB"
      }
    ],
    "WOLF": [
      {
        "path": "research/WOLF/2026-07-12_WOLF_bayesian-intrinsic-growth.md",
        "title": "WOLF bayesian intrinsic growth",
        "date": "2026-07-12",
        "ticker": "WOLF"
      }
    ]
  },
  "📝 行业笔记": {
    "太空产业": [
      {
        "path": "notes/space/2026-07-11_space-economy-moat.md",
        "title": "space economy moat",
        "date": "2026-07-11"
      },
      {
        "path": "notes/space/2026-07-12_space-economy-deep-research.md",
        "title": "space economy deep research",
        "date": "2026-07-12"
      },
      {
        "path": "notes/space/2026-07-12_space-economy-vision.md",
        "title": "space economy vision",
        "date": "2026-07-12"
      },
      {
        "path": "notes/space/2026-07-12_space-industry-investment-report.md",
        "title": "space industry investment report",
        "date": "2026-07-12"
      }
    ]
  },
  "📰 美股收盘日报": {
    "2026年07月": [
      {
        "path": "notes/美股收盘日报/美股收盘日报_2026-07-10.md",
        "title": "美股收盘日报",
        "date": "2026-07-10"
      }
    ]
  }
};
