// Auto-generated by build_tree.py. Do not edit manually.
const TREE_DATA = {
  "📊 个股研究": {
    "PLTR": [
      {
        "path": "research/PLTR/2026-07-11_buyside-memo.md",
        "title": "buyside memo",
        "date": "2026-07-11",
        "ticker": "PLTR"
      },
      {
        "path": "research/PLTR/2026-07-12_chronicle.md",
        "title": "chronicle",
        "date": "2026-07-12",
        "ticker": "PLTR"
      }
    ],
    "RKLB": [
      {
        "path": "research/RKLB/2026-07-11_buyside-memo.md",
        "title": "buyside memo",
        "date": "2026-07-11",
        "ticker": "RKLB"
      },
      {
        "path": "research/RKLB/2026-07-12_biography.md",
        "title": "biography",
        "date": "2026-07-12",
        "ticker": "RKLB"
      },
      {
        "path": "research/RKLB/2026-07-12_corporate-chronicle.md",
        "title": "corporate chronicle",
        "date": "2026-07-12",
        "ticker": "RKLB"
      },
      {
        "path": "research/RKLB/2026-07-12_investment-audit.md",
        "title": "investment audit",
        "date": "2026-07-12",
        "ticker": "RKLB"
      },
      {
        "path": "research/RKLB/2026-07-14_competitor-macro-analysis.md",
        "title": "competitor macro analysis",
        "date": "2026-07-14",
        "ticker": "RKLB"
      }
    ],
    "WOLF": [
      {
        "path": "research/WOLF/2026-07-12_bayesian-intrinsic-growth.md",
        "title": "bayesian intrinsic growth",
        "date": "2026-07-12",
        "ticker": "WOLF"
      }
    ]
  },
  "📝 行业笔记": {
    "太空产业": [
      {
        "path": "notes/space/2026-07-11_space-economy-moat.md",
        "title": "space economy moat",
        "date": "2026-07-11"
      },
      {
        "path": "notes/space/2026-07-12_space-economy-deep-research.md",
        "title": "space economy deep research",
        "date": "2026-07-12"
      },
      {
        "path": "notes/space/2026-07-12_space-economy-vision.md",
        "title": "space economy vision",
        "date": "2026-07-12"
      },
      {
        "path": "notes/space/2026-07-12_space-industry-investment-report.md",
        "title": "space industry investment report",
        "date": "2026-07-12"
      }
    ]
  },
  "📰 美股收盘日报": {
    "2026年07月": [
      {
        "path": "notes/美股收盘日报/美股收盘日报_2026-07-10.md",
        "title": "美股收盘日报",
        "date": "2026-07-10"
      },
      {
        "path": "notes/美股收盘日报/美股收盘日报_2026-07-13.md",
        "title": "美股收盘日报",
        "date": "2026-07-13"
      }
    ]
  }
};
